FROM node:24
WORKDIR /app
EXPOSE 3000
RUN mkdir -p /home/appuser && chmod -R 777 /home/appuser
RUN mkdir -p /pnpm && chmod -R 777 /pnpm

# Ensure /app and node_modules directory is writable by any user
RUN mkdir -p /app/node_modules && chmod -R 777 /app/node_modules

RUN npm i -g pnpm

RUN echo "store-dir=/pnpm/store" >> /etc/npmrc

CMD ["sh", "-c", "cp /run/secrets/npmrc ~/.npmrc && pnpm install --frozen-lockfile && pnpm run dev"]
