FROM amazoncorretto:21-alpine-jdk
RUN apk add --no-cache maven
EXPOSE 8443
WORKDIR /app/suorituspalvelu-service
CMD ["mvn", "scala:run", "-DmainClass=fi.oph.suorituspalvelu.DevApp", "-Dmaven.test.skip=true"]
