FROM node:22-alpine
WORKDIR /app
EXPOSE 3000

# Create cache directories with proper permissions
RUN mkdir -p /tmp/.npm && chmod -R 777 /tmp/.npm

# Ensure /app and node_modules directory is writable by any user
RUN mkdir -p /app/node_modules && chmod -R 777 /app/node_modules

CMD ["sh", "-c", "cp /run/secrets/npmrc ~/.npmrc && npm ci && npm run dev"]
