package fi.oph.suorituspalvelu.security

object SecurityConstants {

  final val OPH_ORGANISAATIO_OID                    = "1.2.246.562.10.00000000001"

  final val SECURITY_ROOLI_PREFIX                   = "ROLE_APP_"

  final val SECURITY_ROOLI_REKISTERINPITAJA         = SECURITY_ROOLI_PREFIX + "SUORITUSREKISTERI_CRUD"
  final val SECURITY_ROOLI_HAKENEIDEN_KATSELIJA     = SECURITY_ROOLI_PREFIX + "SUORITUSPALVELU_HAKENEET_OPPIJAT_READ"
  final val SECURITY_ROOLI_ORGANISAATION_KATSELIJA  = SECURITY_ROOLI_PREFIX + "SUORITUSPALVELU_ORGANISAATION_OPPIJAT_READ"
  final val SECURITY_ROOLI_OPH_PALVELUKAYTTAJA      = SECURITY_ROOLI_PREFIX + "SUORITUSPALVELU_PALVELUKAYTTAJA_OPH"
  final val SECURITY_ROOLI_ULKOINEN_PALVELUKAYTTAJA = SECURITY_ROOLI_PREFIX + "SUORITUSPALVELU_PALVELUKAYTTAJA_ULKOINEN"

  final val SECURITY_ROOLI_REKISTERINPITAJA_FULL    = SECURITY_ROOLI_REKISTERINPITAJA + "_" + OPH_ORGANISAATIO_OID

  val ROOLIT_OPPIJA_HAULLE = Set(SECURITY_ROOLI_HAKENEIDEN_KATSELIJA, SECURITY_ROOLI_ORGANISAATION_KATSELIJA)
}
