package fi.oph.suorituspalvelu.security

object SecurityConstants {

  final val OPH_ORGANISAATIO_OID                    = "1.2.246.562.10.00000000001"

  final val SECURITY_ROOLI_PREFIX                   = "ROLE_APP_"

  final val SECURITY_ROOLI_REKISTERINPITAJA         = SECURITY_ROOLI_PREFIX + "SUORITUSPALVELU_PAAKAYTTAJA"
  final val SECURITY_ROOLI_HAKENEIDEN_KATSELIJA     = SECURITY_ROOLI_PREFIX + "SUORITUSPALVELU_HAKENEIDEN_KATSELIJA"
  final val SECURITY_ROOLI_OPPIJOIDEN_KATSELIJA     = SECURITY_ROOLI_PREFIX + "SUORITUSPALVELU_OPPIJOIDEN_KATSELIJA"
  final val SECURITY_ROOLI_SISAISET_RAJAPINNAT      = SECURITY_ROOLI_PREFIX + "SUORITUSPALVELU_SISAISET_RAJAPINNAT"
  final val SECURITY_ROOLI_ULKOISET_RAJAPINNAT      = SECURITY_ROOLI_PREFIX + "SUORITUSPALVELU_ULKOISET_RAJAPINNAT"
  final val SECURITY_ROOLI_SUPA_VALINTAKAYTTAJA     = SECURITY_ROOLI_PREFIX + "SUORITUSPALVELU_VALINTOJEN_TOTEUTTAMINEN_HARKINNANVARAISUUS" //Fixme oikea oikeus kun lisätty, placeholder vain.

  final val SECURITY_ROOLI_REKISTERINPITAJA_FULL    = SECURITY_ROOLI_REKISTERINPITAJA + "_" + OPH_ORGANISAATIO_OID

  val ROOLIT_OPPIJA_HAULLE = Set(SECURITY_ROOLI_HAKENEIDEN_KATSELIJA, SECURITY_ROOLI_OPPIJOIDEN_KATSELIJA)
}
