name: setup-node-env
description: 'Setup Node.js environment'
inputs:
  project_path:
    description: Path to the package-lock.json
    required: true
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        run_install: false
        package_json_file: ${{ inputs.project_path }}/package.json
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
        cache-dependency-path: ${{ inputs.project_path }}/pnpm-lock.yaml
        registry-url: 'https://npm.pkg.github.com'
        scope: '@opetushallitus'
    - uses: actions/cache@v4
      id: node_modules-cache
      with:
        path: ${{ github.workspace }}/${{ inputs.project_path }}/node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles(format('{0}/pnpm-lock.yaml', inputs.project_path)) }}
    - name: Install npm dependencies
      if: steps.node_modules-cache.outputs.cache-hit != 'true'
      shell: bash
      run: cd ${{inputs.project_path}} && pnpm install --frozen-lockfile
