CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TYPE lahde AS ENUM ('KOSKI', 'YTR', 'VIRTA', 'VIRKAILIJA');

-- taulu lisätty jotta voidaa lukita yksittäinen oppija
CREATE TABLE IF NOT EXISTS oppijat (
    oppijanumero                VARCHAR PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS versiot (
    tunniste                    UUID PRIMARY KEY,
    use_versio_tunniste         UUID REFERENCES versiot (tunniste),
    oppijanumero                VARCHAR NOT NULL REFERENCES oppijat (oppijanumero),
    voimassaolo                 TSTZRANGE NOT NULL,
    lahde                       lahde NOT NULL,
    data_json                   JSONB,
    data_xml                    XML,
    EXCLUDE USING gist (oppijanumero WITH =, lahde WITH =, voimassaolo WITH &&),
    CHECK ((lahde='KOSKI'       AND data_json IS NOT NULL   AND data_xml IS NULL) OR
           (lahde='YTR'         AND data_json IS NOT NULL   AND data_xml IS NULL) OR
           (lahde='VIRTA'       AND data_json IS NULL       AND data_xml IS NOT NULL) OR
           (lahde='VIRKAILIJA'  AND data_json IS NOT NULL   AND data_xml IS NULL))
);

--Vähän epäselvää onko tämä taulu tarpeellinen, vai halutaanko kaikki eri tyypit erikoistuneisiin tauluihin. Tätä voi kuitenkin käyttää sitä odotellessa.
CREATE TABLE IF NOT EXISTS geneeriset_opiskeluoikeudet (
    tunniste INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    versio_tunniste UUID REFERENCES versiot (tunniste) ON DELETE CASCADE,
    oid VARCHAR NOT NULL,
    tyyppi VARCHAR NOT NULL,
    oppilaitos_oid VARCHAR NOT NULL,
    tila JSONB
);
CREATE INDEX geneeriset_opiskeluoikeudet_versio_tunniste_idx ON geneeriset_opiskeluoikeudet (versio_tunniste);

CREATE TABLE IF NOT EXISTS ammatilliset_opiskeluoikeudet (
    tunniste INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    versio_tunniste UUID REFERENCES versiot (tunniste) ON DELETE CASCADE,
    oid VARCHAR NOT NULL,
    oppilaitos_oid VARCHAR NOT NULL,
    tila JSONB
);
CREATE INDEX ammatilliset_opiskeluoikeudet_versio_tunniste_idx ON ammatilliset_opiskeluoikeudet (versio_tunniste);

CREATE TABLE IF NOT EXISTS tuvat (
    versio_tunniste         UUID REFERENCES versiot (tunniste) ON DELETE CASCADE,
    opiskeluoikeus_tunniste INT REFERENCES geneeriset_opiskeluoikeudet (tunniste) ON DELETE CASCADE,
    koodi                   VARCHAR NOT NULL,
    vahvistuspaivamaara     DATE
);
CREATE INDEX tuvat_versio_tunniste_idx ON tuvat (versio_tunniste);

CREATE TABLE IF NOT EXISTS telmat (
    versio_tunniste         UUID REFERENCES versiot (tunniste) ON DELETE CASCADE,
    opiskeluoikeus_tunniste INT REFERENCES ammatilliset_opiskeluoikeudet (tunniste) ON DELETE CASCADE,
    koodi                   VARCHAR NOT NULL
);
CREATE INDEX telmat_versio_tunniste_idx ON telmat (versio_tunniste);

CREATE TABLE IF NOT EXISTS perusopetuksen_opiskeluoikeudet (
    tunniste INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    versio_tunniste UUID REFERENCES versiot (tunniste) ON DELETE CASCADE,
    oid VARCHAR NOT NULL,
    oppilaitos_oid VARCHAR NOT NULL,
    lisatiedot JSONB,
    tila JSONB
);
CREATE INDEX perusopetuksen_opiskeluoikeudet_versio_tunniste_idx ON perusopetuksen_opiskeluoikeudet (versio_tunniste);

CREATE TABLE IF NOT EXISTS perusopetuksen_vuosiluokat (
    versio_tunniste         UUID REFERENCES versiot (tunniste) ON DELETE CASCADE,
    opiskeluoikeus_tunniste INT REFERENCES perusopetuksen_opiskeluoikeudet (tunniste) ON DELETE CASCADE,
    nimi                    VARCHAR NOT NULL,
    koodi                   VARCHAR NOT NULL,
    alkamispaiva            DATE
);
CREATE INDEX perusopetuksen_vuosiluokat_versio_tunniste_idx ON perusopetuksen_vuosiluokat (versio_tunniste);

CREATE TABLE IF NOT EXISTS perusopetuksen_oppimaarat (
    tunniste                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opiskeluoikeus_tunniste INT REFERENCES perusopetuksen_opiskeluoikeudet (tunniste) ON DELETE CASCADE,
    versio_tunniste         UUID REFERENCES versiot (tunniste) ON DELETE CASCADE,
    organisaatio_oid        VARCHAR NOT NULL,
    tila                    VARCHAR NOT NULL,
    tilakoodisto            VARCHAR NOT NULL,
    tilaversio              INT NOT NULL,
    vahvistuspaivamaara     DATE
);
CREATE INDEX perusopetuksen_oppimaarat_versio_tunniste_idx ON perusopetuksen_oppimaarat (versio_tunniste);

CREATE TABLE IF NOT EXISTS perusopetuksen_oppiaineet (
    oppimaara_tunniste      INT REFERENCES perusopetuksen_oppimaarat (tunniste) ON DELETE CASCADE,
    nimi                    VARCHAR NOT NULL,
    koodi                   VARCHAR NOT NULL,
    arvosana                VARCHAR NOT NULL
);
CREATE INDEX perusopetuksen_oppiaineet_oppimaara_tunniste_idx ON perusopetuksen_oppiaineet (oppimaara_tunniste);

CREATE TABLE IF NOT EXISTS nuorten_perusopetuksen_oppiaineen_oppimaarat (
    versio_tunniste         UUID REFERENCES versiot (tunniste) ON DELETE CASCADE,
    opiskeluoikeus_tunniste INT REFERENCES perusopetuksen_opiskeluoikeudet (tunniste) ON DELETE CASCADE,
    nimi                    VARCHAR NOT NULL,
    koodi                   VARCHAR NOT NULL,
    arvosana                VARCHAR NOT NULL
);
CREATE INDEX nuorten_perusopetuksen_oppiaineen_oppimaarat_versio_tunniste_idx ON nuorten_perusopetuksen_oppiaineen_oppimaarat (versio_tunniste);

CREATE TABLE IF NOT EXISTS ammatilliset_tutkinnot (
    tunniste                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opiskeluoikeus_tunniste INT REFERENCES ammatilliset_opiskeluoikeudet (tunniste) ON DELETE CASCADE,
    versio_tunniste         UUID REFERENCES versiot (tunniste) ON DELETE CASCADE,
    nimi                    VARCHAR NOT NULL,
    tyyppi                  VARCHAR NOT NULL,
    koodisto                VARCHAR NOT NULL,
    koodistoversio          INT NOT NULL,
    tila                    VARCHAR NOT NULL,
    tilakoodisto            VARCHAR NOT NULL,
    tilaversio              INT NOT NULL,
    suoritustapa            VARCHAR NOT NULL,
    suoritustapakoodisto    VARCHAR NOT NULL,
    suoritustapaversio      INT NOT NULL,
    keskiarvo               DECIMAL(3, 1),
    vahvistuspaivamaara     DATE
);
CREATE INDEX ammatilliset_tutkinnot_versio_tunniste_idx ON ammatilliset_tutkinnot (versio_tunniste);

CREATE TABLE IF NOT EXISTS ammatillisen_tutkinnon_osat (
    tunniste                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tutkinto_tunniste       INT REFERENCES ammatilliset_tutkinnot (tunniste) ON DELETE CASCADE,
    nimi                    VARCHAR NOT NULL,
    koodi                   VARCHAR NOT NULL,
    koodisto                VARCHAR, --Fixme ehkä, NOT NULL-constraint poistettu ainakin väliaikaisesti. Ilmeisesti joissain tutkinnon osissa voi olla koulutusmoduuli->tunniste->koodistoUri -kenttä tyhjänä, esimerkiksi QA-Koskessa ja massaluovutusrajapinnan skeemassa.
    koodistoversio          INT NOT NULL,
    yto                     BOOLEAN NOT NULL,
    arvosana                VARCHAR,
    arvosanaasteikko        VARCHAR,
    arvosanaversio          INT,
    laajuus                 INT,
    laajuuskoodi            VARCHAR,
    laajuuskoodisto         VARCHAR,
    laajuusversio           INT
);
CREATE INDEX ammatillisen_tutkinnon_osat_tutkinto_tunniste_idx ON ammatillisen_tutkinnon_osat (tutkinto_tunniste);

CREATE TABLE IF NOT EXISTS ammatillisen_tutkinnon_osaalueet (
    osa_tunniste            INT REFERENCES ammatillisen_tutkinnon_osat (tunniste) ON DELETE CASCADE,
    nimi                    VARCHAR NOT NULL,
    koodi                   VARCHAR NOT NULL,
    koodisto                VARCHAR, --Fixme ehkä, NOT NULL-constraint poistettu ainakin väliaikaisesti. Ilmeisesti joissain tutkinnon osissa voi olla koulutusmoduuli->tunniste->koodistoUri -kenttä tyhjänä, esimerkiksi QA-Koskessa ja massaluovutusrajapinnan skeemassa.
    koodistoversio          INT NOT NULL,
    arvosana                VARCHAR,
    arvosanaasteikko        VARCHAR,
    arvosanaversio          INT,
    laajuus                 INT,
    laajuuskoodi            VARCHAR,
    laajuuskoodisto         VARCHAR,
    laajuusversio           INT
);
CREATE INDEX ammatillisen_tutkinnon_osaalueet_osa_tunniste_idx ON ammatillisen_tutkinnon_osaalueet (osa_tunniste);

CREATE TABLE IF NOT EXISTS opiskeluoikeudet (
    tunniste                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    versio_tunniste         UUID REFERENCES versiot (tunniste),
    tyyppi                  VARCHAR NOT NULL,
    alkupvm                 DATE,
    loppupvm                DATE,
    tila                    VARCHAR,
    UNIQUE (versio_tunniste, tyyppi)
);
CREATE INDEX opiskeluoikeudet_versio_tunniste_idx ON opiskeluoikeudet (versio_tunniste);

CREATE TABLE IF NOT EXISTS yotutkinnot (
    tunniste                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    versio_tunniste         UUID REFERENCES versiot (tunniste)
);
CREATE INDEX yotutkinto_versio_tunniste_idx ON yotutkinnot (versio_tunniste);
