name: Suorituspalvelun build workflow
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"
env:
  HUSKY: 0
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-and-build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version-file: ".java-version"
          distribution: "corretto"
          cache: "maven"
      - uses: ./.github/actions/setup-node-env
        with:
          project_path: suorituspalvelu-ui
      - name: Build and copy frontend to backend static-dir
        run: |
          cd suorituspalvelu-ui
          npm run build-and-copy

      - name: Build Scala projects
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean package

      - uses: actions/cache@v4
        id: restore-build
        with:
          path: |
            suorituspalvelu-service/target
            suorituspalvelu-domain/target
            suorituspalvelu-paattelyt/target
            suorituspalvelu-shared/target
          key: ${{ github.sha }}
  lint-and-test-frontend:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./suorituspalvelu-ui
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-env
        with:
          project_path: suorituspalvelu-ui
      - name: Check types
        run: npm run typecheck
      - name: Run linter
        run: npm run lint
      - name: Run unit tests
        run: npm run test
  test-playwright:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./suorituspalvelu-ui
    strategy:
      fail-fast: true # Lopetetaan, jos testit epäonnistuu yhdellä selaimella
      matrix:
        browser: [chromium, firefox]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-env
        with:
          project_path: suorituspalvelu-ui
      - name: Build app
        run: npm run build:test
      - name: Run Playwright tests
        env:
          PLAYWRIGHT_ARGS: --project=${{ matrix.browser }}
        run: npm run start-and-test-playwright-docker
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 10
          if-no-files-found: ignore
  deploy-container:
    needs:
      - test-and-build-backend
      - lint-and-test-frontend
      - test-playwright
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: restore-build
        with:
          path: |
            suorituspalvelu-service/target
            suorituspalvelu-domain/target
            suorituspalvelu-paattelyt/target
            suorituspalvelu-shared/target
          key: ${{ github.sha }}

      - name: Build and deploy Docker container
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh

          export ARTIFACT_NAME="suorituspalvelu"
          mv suorituspalvelu-service/target/suorituspalvelu-service-exec.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar
          cp -vr suorituspalvelu-service/src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/
          export BASE_IMAGE="baseimage-fatjar-openjdk21:master"
          ./ci-tools/common/pull-image.sh
          ./ci-tools/github-build/build-fatjar.sh $ARTIFACT_NAME
          ./ci-tools/github-build/upload-image.sh $ARTIFACT_NAME
